analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - identifier_name
  - line_length
  - nesting
  - todo
